mutation AddVehicle(
  $make: String!
  $model: String!
  $year: Int!
  $topSpeed: Int
  $power: Int
  $weight: Int
  $engine: String
  $torque: Int
  $sixty: Float
  $price: Int
) {
  createVehicle(
    make: $make
    model: $model
    year: $year
    topSpeed: $topSpeed
    power: $power
    weight: $weight
    engine: $engine
    torque: $torque
    sixty: $sixty
    price: $price
  ) {
    id
  }
}
