mutation AddVehicle(
  $make: String!
  $model: String!
  $year: String!
  $topSpeed: String
  $power: String
  $weight: String
  $engine: String
  $torque: String
  $sixty: String
  $price: String
  $vtype: String
) {
  createVehicle(
    make: $make
    model: $model
    year: $year
    topSpeed: $topSpeed
    power: $power
    weight: $weight
    engine: $engine
    torque: $torque
    sixty: $sixty
    price: $price
    vtype: $vtype
  ) {
    id
  }
}
