query AllVehicles($searchString: String) {
  Vehicles(searchString: $searchString) {
    id
    make
    model
    image
    year
    topSpeed
    power
    weight
    engine
    torque
    sixty
    price
    vtype
  }
}